name: chakri_ase_company
description: Chakri Ase Company
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shared_preferences: ^2.0.6
  http: ^0.13.3
  dio: ^4.0.0
  flutter_html: ^2.2.1

  intl: ^0.17.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.0
  rflutter_alert: ^2.0.4
  html_editor_enhanced: ^2.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
